### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by dazWiLLiE** [Thrilleratplay/coreboot-builder-scripts#19] opened 2022-05-26 21:59 UTC
I must be missing something, when I execute `./build.sh -i t430` I get a bunch of errors.

First time I ran build.sh it downloaded everything (i guess), and errored out (same error message).
When I run it now, I get this:

```
❯ pwd
/home/username/coreboot-builder-scripts
```

```./build.sh -i t430
Beginning download of fc5b1b96829785ca28c8b211545b1ae5c73a4b53211021fd2410f2a6798776b0  coreboot-4.4-relnotes.txt...
unxz: (stdin): File format not recognized
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
unxz: (stdin): File format not recognized
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Downloading fc5b1b96829785ca28c8b211545b1ae5c73a4b53211021fd2410f2a6798776b0  coreboot-4.4-relnotes.txt complete
cp: cannot create regular file '/home/coreboot/cb_build/configs/defconfig': No such file or directory
Using default config
make: *** No rule to make target 'defconfig'.  Stop.
make: *** No rule to make target 'nconfig'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
Uh oh. Things did not go according to plan.
```

Docker is installed and running. I'm on Arch.

Edit:
Apparently --bleeding-edge works. So something is wonky with the latest release.

**Comment by Thrilleratplay** [comment] 2022-05-27 00:23
huh.  I am not sure why it is trying to pull and build coreboot v4.4.  I'm not surprised it wouldn't build using the current docker image as the build system has changed significantly since 6 years ago..  Did you try another command that partially ran before running `./build.sh -i t430`?  There could have been cached files from a bad pull that caused that.

**Comment by dazWiLLiE** [comment] 2022-05-27 09:30
Well.. I bricked my thinkpad. The build went fine, I proceeded to change bootsplash,

```
convert bootsplash.jpg -alpha set -verbose -depth 32 bootsplash.bmp
util/cbfstool/cbfstool build/coreboot_lenovo-t430-complete.rom add -f splash/bootsplash.bmp -c lzma -n bootsplash.bmp.lzma -t raw
```
tried to flash with t430/flashrom.sh, didn't work, complained about readonly chips. So I used the command I've used before instead (big mistake):

`flashrom -p internal:laptop=force_I_want_a_brick -w build/coreboot_lenovo-t430-complete.rom --ifd -i bios -N
`

Now on boot it only shows a white screen.

I guess the problem was doing it without the layout?

Anyway, ordered a Pomona 5250 so we'll see how it goes.

**Comment by Thrilleratplay** [comment] 2022-05-27 18:42
Thew white screen may just be bootsplash displaying incorrectly (it is insanely finicky).  Try to let it boot to the OS and see if anything changes.  If so, the initial failed flashrom attempt may have created a backup you can restore from.

Did you have coreboot installed before, if so did you use 1vyrain?  If I remember correctly if you use the `--ifd` flag with `-i bios`it will read the existing idf from the BIOS, but because of options like `force_I_want_a_brick`, i prefer the config file option to prevent trying to debug situations like this.

Good news, external flashing is really not too different from what you have already done or difficult after getting set up if you have a Pomona clip and a CH341A or Raspberry Pi.  Just take your time and be sure to double then triple check the wiring before running flashrom again.  The bad news....this is a T430...and is a pain to flash externally as the chips are on the bottom of the motherboard behind a metal plate.  The laptop will effectively need to the disassembled to remove the motherboard.  Here is a link to the [T430 hardware maintenance manual](https://thinkpads.com/support/hmm/hmm_pdf/t430_t430i_hmm_en_0b48304_03.pdf) which could be helpful.

**Comment by dazWiLLiE** [comment] 2022-06-04 11:06
Thanks for the info. I deassembled the t430, downloaded skulls, located the chip (which apparently is a 25Q32BVSIG), and flashed the top. First try failed the verification after flash, second try succeded. Now when I try to boot, the power button lights up, and then it turns off.

I followed [this guide](https://github.com/merge/skulls/blob/master/t430/README.md).

`Flashing the left chip is optional but highly recommended.`

I tried to flash that multiple times, readjusting the clip, but flashrom told me it couldn't find any chip. (Perhaps I need to try again) 

Do you think I need to flash the bottom too, and that that is the problem?

**Comment by Thrilleratplay** [comment] 2022-06-04 20:44
Assuming this is the 8M chip, for the T430, I would say it is in your best interest to flash it as it contains the IFD write lock flag.  Disabling this will allow you to flash internally without disassembling your laptop.  It also contains the GBE blob, which is mostly benign, and the ME blob that most people choose to neuter using [me_cleaner](https://github.com/corna/me_cleaner).  Ultimately, it is your device and you can do whatever you want with it.

**Comment by Thrilleratplay** [comment] 2022-07-23 17:33
@dazWiLLiE I found the cause of you original issue and pushed a fix.  I'm not sure if something changed or it worked by chance for the longest time.  

I am going to close this issue but feel free to reopen if you still are having issues.

**Closed by Thrilleratplay** 2022-07-23 17:33 UTC
